Repository m3db/m3, pull requests merged in 2019-03, with the labels that each got.

#1420 construct service once and have it shared by tchannel and http servers
  src/dbnode/integration/serve.go
  src/dbnode/network/server/httpjson/node/server.go
  src/dbnode/network/server/tchannelthrift/node/server.go
  src/dbnode/server/server.go
Labels: T: Cleanup, T: Memory Utilization, T: Optimization, T: Perf, T: Refactor, area:db

#1476 Fix annotation pooling
  src/dbnode/network/server/tchannelthrift/node/service.go
  src/dbnode/storage/shard.go
  src/dbnode/storage/shard_insert_queue.go
  src/dbnode/storage/shard_ref_count_test.go
  src/dbnode/storage/shard_test.go
  src/dbnode/storage/types.go
  src/dbnode/ts/types.go
  src/dbnode/ts/write_batch.go
  src/dbnode/ts/write_batch_mock.go
  src/dbnode/ts/write_batch_test.go
Labels: PR: Awaiting Review [db], PR: Review Priority High, T: Bug, area:db

#1482 Improve M3DBs ability to apply back pressure on writes
  src/dbnode/network/server/tchannelthrift/node/service.go
  src/dbnode/network/server/tchannelthrift/node/service_test.go
  src/dbnode/persist/fs/commitlog/commit_log.go
  src/dbnode/persist/fs/commitlog/commit_log_mock.go
  src/dbnode/persist/fs/commitlog/commit_log_test.go
  src/dbnode/persist/fs/commitlog/types.go
  src/dbnode/storage/database.go
  src/dbnode/storage/database_test.go
  src/dbnode/storage/options.go
  src/dbnode/storage/storage_mock.go
  src/dbnode/storage/types.go
  src/dbnode/x/xcounter/frequency_counter.go
  src/dbnode/x/xcounter/frequency_counter_test.go
  src/dbnode/x/xcounter/options.go
Labels: PR: Awaiting Review [db], PR: Review Priority High, T: Reliability, area:db

#1491 Add operational guide on tuning availability, consistency, and durability + make ignoring corrupt commitlogs on bootstrap default in all sample YAMLs
  docs/operational_guide/availability_consistency_durability.md
  kube/bundle.yaml
  kube/m3dbnode-configmap.yaml
  mkdocs.yml
  scripts/development/m3_stack/m3dbnode.yml
  src/dbnode/config/m3dbnode-all-config.yml
  src/dbnode/config/m3dbnode-cluster-template.yml
  src/dbnode/config/m3dbnode-local-etcd.yml
  src/dbnode/config/m3dbnode-local.yml
  src/query/benchmark/benchmarker/main/m3dbnode-local-config.yaml
  src/query/benchmark/configs/m3db_config.yaml
  src/query/benchmark/configs/multi_node_setup/m3dbnode-server1-config.yaml
  src/query/benchmark/configs/multi_node_setup/m3dbnode-server2-config.yaml
  src/query/benchmark/configs/multi_node_setup/m3dbnode-server3-config.yaml
Labels: area:documentation

#1421 Use Seek() and Read() APIs for index/data files instead of mmap + share expensive seeker resources among seekers
  src/dbnode/generated/mocks/generate.go
  src/dbnode/persist/fs/commitlog/files.go
  src/dbnode/persist/fs/commitlog/reader.go
  src/dbnode/persist/fs/files.go
  src/dbnode/persist/fs/fs_mock.go
  src/dbnode/persist/fs/index_lookup.go
  src/dbnode/persist/fs/index_lookup_prop_test.go
  src/dbnode/persist/fs/index_lookup_test.go
  src/dbnode/persist/fs/msgpack/decoder.go
  src/dbnode/persist/fs/msgpack/decoder_test.go
  src/dbnode/persist/fs/msgpack/encoder_decoder_bench_test.go
  src/dbnode/persist/fs/msgpack/roundtrip_test.go
  src/dbnode/persist/fs/msgpack/stream.go
  src/dbnode/persist/fs/msgpack/stream_test.go
  src/dbnode/persist/fs/msgpack/summary_token.go
  src/dbnode/persist/fs/read.go
  src/dbnode/persist/fs/read_decode_stream.go
  src/dbnode/persist/fs/retriever.go
  src/dbnode/persist/fs/retriever_concurrent_test.go
  src/dbnode/persist/fs/seek.go
  src/dbnode/persist/fs/seek_manager.go
  src/dbnode/persist/fs/seek_manager_test.go
  src/dbnode/persist/fs/seek_test.go
  src/dbnode/persist/fs/types.go
  src/dbnode/server/server.go
  src/dbnode/storage/block/types.go
Labels: C: Filesystem, C: Storage, PR: Awaiting Review [db], PR: Review Priority High, T: Memory Utilization, T: Optimization, T: Perf, T: Refactor, area:db

#1513 Pin jaeger-client-go to ~2.15
  glide.lock
  glide.yaml
Labels: area:build
