Repository m3db/m3, pull requests merged in 2019-04, with the labels that each got.

#1083 Map of buckets in buffer; setup for out of order writes
  src/cmd/services/m3dbnode/config/config_test.go
  src/cmd/services/m3dbnode/config/pooling.go
  src/cmd/services/m3dbnode/main/main_test.go
  src/dbnode/generated/proto/namespace/namespace.pb.go
  src/dbnode/generated/proto/namespace/namespace.proto
  src/dbnode/network/server/tchannelthrift/node/service.go
  src/dbnode/network/server/tchannelthrift/node/service_test.go
  src/dbnode/retention/config.go
  src/dbnode/retention/options.go
  src/dbnode/retention/retention_mock.go
  src/dbnode/retention/times.go
  src/dbnode/retention/types.go
  src/dbnode/server/server.go
  src/dbnode/storage/bootstrap/process.go
  src/dbnode/storage/database_test.go
  src/dbnode/storage/errors/types.go
  src/dbnode/storage/fs.go
  src/dbnode/storage/index.go
  src/dbnode/storage/namespace.go
  src/dbnode/storage/namespace/config.go
  src/dbnode/storage/namespace/convert.go
  src/dbnode/storage/namespace/namespace_mock.go
  src/dbnode/storage/namespace/options.go
  src/dbnode/storage/namespace/options_test.go
  src/dbnode/storage/namespace/types.go
  src/dbnode/storage/namespace_test.go
  src/dbnode/storage/options.go
  src/dbnode/storage/repair.go
  src/dbnode/storage/result.go
  src/dbnode/storage/series/buffer.go
  src/dbnode/storage/series/buffer_mock.go
  src/dbnode/storage/series/buffer_test.go
  src/dbnode/storage/series/options.go
  src/dbnode/storage/series/reader.go
  src/dbnode/storage/series/series.go
  src/dbnode/storage/series/series_all_test.go
  src/dbnode/storage/series/series_mock.go
  src/dbnode/storage/series/series_test.go
  src/dbnode/storage/series/types.go
  src/dbnode/storage/shard.go
  src/dbnode/storage/shard_index_test.go
  src/dbnode/storage/shard_test.go
  src/dbnode/storage/storage_mock.go
  src/dbnode/storage/types.go
  src/query/api/v1/handler/database/create_test.go
  src/query/api/v1/handler/namespace/add_test.go
  src/query/api/v1/handler/namespace/get_test.go
Labels: PR: Awaiting Review [db], PR: Review Priority High

#1554 Add tips for writing docs, tweak doc scripts
  Makefile
  docs/Dockerfile
  docs/misc/writing_docs.md
  docs/overview/components.md
  docs/overview/media.md
  docs/overview/motivation.md
  mkdocs.yml
Labels: area:documentation

#1574 [dbnode] Fix index flush recovery when previous flush attempts have failed
  CHANGELOG.md
  src/dbnode/persist/fs/files.go
  src/dbnode/persist/fs/files_test.go
  src/dbnode/persist/fs/index_write.go
  src/dbnode/persist/fs/persist_manager_test.go
  src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
  src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_data_test.go
  src/dbnode/storage/namespace_test.go
Labels: area:db

#1581 [dbnode] Filter out corrupt commit log files that were not present before the node started in the commit log bootstrapper
  CHANGELOG.md
  src/dbnode/persist/fs/commitlog/commit_log_test.go
  src/dbnode/persist/fs/commitlog/iterator.go
  src/dbnode/persist/fs/commitlog/types.go
  src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
Labels: C: Bootstrap, C: Commit Log, PR: Review Priority High, T: Bug, area:db

#1233 Implement a DecodeLogMetadataFast function 10x faster than current decode methods
  src/dbnode/persist/fs/msgpack/decoder_fast.go
  src/dbnode/persist/fs/msgpack/encoder_decoder_bench_test.go
  src/dbnode/persist/fs/msgpack/encoder_decoder_prop_test.go
  src/dbnode/persist/fs/msgpack/encoder_fast.go
Labels: C: Filesystem, PR: Awaiting Review [db], PR: Review Priority Low, T: Optimization, T: Perf, T: Refactor, area:db

#1576 Open new commitlogs async
  docs/code_assets/README.md
  docs/code_assets/commitlog/queue.monopic
  src/dbnode/persist/fs/commitlog/README.md
  src/dbnode/persist/fs/commitlog/commit_log.go
  src/dbnode/persist/fs/commitlog/commit_log_conc_test.go
  src/dbnode/persist/fs/commitlog/commit_log_test.go
  src/dbnode/persist/fs/commitlog/files.go
  src/dbnode/persist/fs/commitlog/read_write_prop_test.go
  src/dbnode/persist/fs/files.go
  src/dbnode/persist/fs/files_test.go
Labels: C: Commit Log, PR: Review Priority Medium, T: Optimization, T: Perf, area:db
