Repository m3db/m3, pull requests merged in 2020-10, with the labels that each got.

#2668 [dbnode] Large tile aggregation improvements
  src/dbnode/integration/large_tiles_test.go
  src/dbnode/server/options.go
  src/dbnode/server/server.go
  src/dbnode/storage/database.go
  src/dbnode/storage/database_test.go
  src/dbnode/storage/index.go
  src/dbnode/storage/index_test.go
  src/dbnode/storage/lease_verifier.go
  src/dbnode/storage/namespace.go
  src/dbnode/storage/namespace_test.go
  src/dbnode/storage/options.go
  src/dbnode/storage/readonly_index_proxy.go
  src/dbnode/storage/readonly_index_proxy_test.go
  src/dbnode/storage/shard.go
  src/dbnode/storage/shard_test.go
  src/dbnode/storage/storage_mock.go
  src/dbnode/storage/types.go
Labels: area:tiles

#2644 [dbnode] Extended namespace options
  scripts/proto-gen.sh
  src/cmd/services/m3dbnode/main/common_test.go
  src/cmd/tools/dtest/harness/harness.go
  src/dbnode/generated/proto/namespace/namespace.pb.go
  src/dbnode/generated/proto/namespace/namespace.proto
  src/dbnode/integration/dynamic_namespace_add_test.go
  src/dbnode/integration/dynamic_namespace_delete_test.go
  src/dbnode/integration/ns_admin_integration_test.go
  src/dbnode/namespace/convert.go
  src/dbnode/namespace/convert_prop_test.go
  src/dbnode/namespace/convert_test.go
  src/dbnode/namespace/kvadmin/ns_admin.go
  src/dbnode/namespace/kvadmin/ns_admin_test.go
  src/dbnode/namespace/namespace_mock.go
  src/dbnode/namespace/options.go
  src/dbnode/namespace/options_test.go
  src/dbnode/namespace/types.go
  src/query/api/v1/handler/database/create.go
  src/query/api/v1/handler/database/create_test.go
  src/query/api/v1/handler/namespace/add.go
  src/query/api/v1/handler/namespace/add_test.go
  src/query/api/v1/handler/namespace/common_test.go
  src/query/api/v1/handler/namespace/delete.go
  src/query/api/v1/handler/namespace/get_test.go
  src/query/api/v1/handler/namespace/update.go
  src/query/api/v1/handler/namespace/update_test.go
  src/x/net/http/response.go
  src/x/test/namespace_extended_opts.go
Labels: area:tiles

#2628 [coordinator] Store metrics type into the annotation
  src/cmd/services/m3coordinator/downsample/downsampler.go
  src/cmd/services/m3coordinator/downsample/downsampler_test.go
  src/cmd/services/m3coordinator/downsample/metrics_appender.go
  src/cmd/services/m3coordinator/ingest/write.go
  src/cmd/services/m3coordinator/ingest/write_test.go
  src/dbnode/generated/proto/annotation/annotation.pb.go
  src/dbnode/generated/proto/annotation/annotation.proto
  src/query/api/v1/handler/prometheus/remote/write.go
  src/query/api/v1/handler/prometheus/remote/write_test.go
  src/query/generated/proto/prompb/types.pb.go
  src/query/generated/proto/prompb/types.proto
  src/query/storage/converter.go
  src/query/storage/converter_test.go
  src/query/ts/metadata.go
Labels: area:tiles

#2532 [dbnode] Downsample counter resets
  src/dbnode/encoding/tile/counter_resets_downsampler.go
  src/dbnode/encoding/tile/counter_resets_downsampler_prop_test.go
  src/dbnode/encoding/tile/counter_resets_downsampler_test.go
Labels: area:tiles

#2713 [dbnode] Handle counter resets (controlled by metrics type)
  src/dbnode/encoding/tile/frame_annotations.go
  src/dbnode/encoding/tile/frame_annotations_test.go
  src/dbnode/encoding/tile/frame_units.go
  src/dbnode/encoding/tile/frame_units_test.go
  src/dbnode/encoding/tile/series_block_frame_test.go
  src/dbnode/encoding/tile/types.go
  src/dbnode/generated/mocks/generate.go
  src/dbnode/generated/thrift/rpc.thrift
  src/dbnode/generated/thrift/rpc/rpc.go
  src/dbnode/integration/large_tiles_test.go
  src/dbnode/network/server/tchannelthrift/node/service.go
  src/dbnode/network/server/tchannelthrift/node/service_test.go
  src/dbnode/persist/fs/fs_mock.go
  src/dbnode/persist/fs/streaming_write.go
  src/dbnode/persist/fs/streaming_write_test.go
  src/dbnode/storage/database.go
  src/dbnode/storage/database_test.go
  src/dbnode/storage/namespace.go
  src/dbnode/storage/namespace_test.go
  src/dbnode/storage/shard.go
  src/dbnode/storage/shard_test.go
  src/dbnode/storage/storage_mock.go
  src/dbnode/storage/types.go
  src/dbnode/ts/downsample/counter_resets_downsampler.go
  src/dbnode/ts/downsample/counter_resets_downsampler_prop_test.go
  src/dbnode/ts/downsample/counter_resets_downsampler_test.go
Labels: area:tiles

#2541 [DOCS] Quickstart revamp
  netlify.toml
  site/config.toml
  site/content/docs/_index.md
  site/content/docs/glossary/namespace.md
  site/content/docs/glossary/placement.md
  site/content/docs/glossary/shard.md
  site/content/docs/how_to/aggregator.md
  site/content/docs/how_to/query.md
  site/content/docs/how_to/single_node.md
  site/content/docs/includes/quickstart/create-database.sh
  site/content/docs/includes/quickstart/write-metrics-1.sh
  site/content/docs/includes/quickstart/write-metrics-2.sh
  site/content/docs/includes/quickstart/write-metrics-3.sh
  site/content/docs/integrations/graphite.md
  site/content/docs/quickstart/_index.md
  site/go.mod
  site/go.sum
  site/layouts/shortcodes/apiendpoint.html
  site/layouts/shortcodes/now.html
  site/static/index.html
Labels: area:documentation

#2727 [docs] Fix dumped file names in troubleshooting guide
  site/content/docs/troubleshooting/_index.md
Labels: area:documentation

#2805 [query] count_values label naming fixes
  src/query/functions/aggregation/count_values.go
  src/query/functions/aggregation/count_values_test.go
  src/query/models/tags.go
  src/query/parser/promql/matchers.go
  src/query/parser/promql/parse.go
  src/query/parser/promql/resolve_scalar_test.go
  src/query/test/compatibility/testdata/aggregators.test
Labels: area:query
