Repository m3db/m3, pull requests merged in 2020-11, with the labels that each got.

#2792 [query] sort, topk, bottomk fixes for instant queries
  src/cmd/services/m3query/config/config.go
  src/cmd/services/m3query/config/config_test.go
  src/query/api/v1/handler/prometheus/native/read.go
  src/query/api/v1/handler/prometheus/native/read_common.go
  src/query/api/v1/handler/prometheus/native/read_test.go
  src/query/api/v1/handler/prometheus/remote/read_test.go
  src/query/block/meta.go
  src/query/functions/aggregation/take.go
  src/query/functions/aggregation/take_test.go
  src/query/functions/linear/sort.go
  src/query/functions/linear/sort_test.go
  src/query/functions/utils/heap.go
  src/query/functions/utils/heap_test.go
  src/query/models/query_context.go
  src/query/parser/promql/matchers.go
  src/query/parser/promql/parse_test.go
  src/query/test/compatibility/testdata/aggregators.test
  src/query/test/compatibility/testdata/functions.test
Labels: area:query

#2830 Add GOVERNANCE.md to describe governance
  GOVERNANCE.md
Labels: TSC

#2831 Add coding style guide
  STYLEGUIDE.md
Labels: TSC

#2861 [dbnode] implement deletion method in namespace kvadmin service
  src/dbnode/namespace/kvadmin/ns_admin.go
  src/dbnode/namespace/kvadmin/ns_admin_test.go
Labels: area:db

#2872 [query] Query handlers refactoring
  src/query/api/v1/handler/database/common.go
  src/query/api/v1/handler/namespace/common.go
  src/query/api/v1/handler/placement/common.go
  src/query/api/v1/handler/prometheus/native/read.go
  src/query/api/v1/handler/topic/common.go
  src/query/api/v1/handler/types.go
  src/query/api/v1/httpd/handler.go
  src/query/api/v1/httpd/handler_test.go
  src/query/api/v1/options/handler.go
Labels: area:query

#2832 Update development guide
  .github/pull_request_template.md
  DEVELOPER.md
  DEVELOPMENT.md
  README.md
Labels: TSC

#2779 [dbnode] Remove some dead code from peersSource
  src/dbnode/integration/large_tiles_test.go
  src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
Labels: PR: Review Priority Low
